config/routes.rb
Rails.application.routes.draw do
  resources :videos do
  	collection do
  		get :Search
  	end
  end
  devise_for :users

  root 'videos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: { message: 'は必須です' }
end

app/models/video.rb
class Video < ApplicationRecord
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception
  	before_action :authenticate_user!	#deviseの認証
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

	before_action :set_video, only: [:show, :edit, :update, :destroy]

  def index
  	@videos = Video.all.order(created_at: :desc)
  end

  def new
  	@video = Video.new
  end

  def create
  	@video = Video.new(video_params)
  	@video.user_id = current_user.id
  	if @video.save
  		redirect_to @video
  	else
  		render 'new'
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @video.update(video_params)
  		redirect_to @video
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@video.destroy
  	redirect_to videos_path
  end

  def Search
    @videos = Video.where('title like ?', '%' + params[:search_title] + '%').order(created_at: :desc)
    render 'index'
  end

  private
  	def video_params
  		params.require(:video).permit(:title, :videourl, :text, :username)
  	end

  	def set_video
  		@video = Video.find params[:id]
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningVideos</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="container">
	<header>
	  <nav>
	    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
	    <% if user_signed_in? %> 
	      <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
	      <!-- *_path はUserモデルを作成したときに、
	        deviseにより自動で作成されてますので、rake routesで確認できます -->
	      Logged in as <strong><%= current_user.username %></strong>.
	      <%= link_to 'プロフィール変更', edit_user_registration_path %> |
	      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
	    <% else %>
	      <%= link_to "サインイン", new_user_registration_path %> |
	      <%= link_to "ログイン", new_user_session_path %>
	    <% end %>
	  </nav>
	</header>
  
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

    <%= yield %>
   </div><%# container %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/videos/_form.html.erb
<%= form_for @video do |f| %>
	<% if @video.errors.any? %>
		<%= @video.errors.count %>個のエラーがあります<br>
		<% @video.errors.full_messages.each do |msg| %>
			<%= msg %><br>
		<% end -%>
	<% end -%>

	<p>タイトル</p>
	<%= f.text_field :title %><br>
	<p>動画URL</p>
	<%= f.text_field :videourl %><br>
	<p>紹介文</p>
	<%= f.text_area :text %><br>
	<%= f.submit %>
<% end -%>

app/views/videos/edit.html.erb
<h2>動画情報編集</h2>

<%= render 'form' %>

app/views/videos/index.html.erb
<div id="header">
	<h1>トップページ</h1>
	<%= link_to '新規動画登録', new_video_path %>
	<%= form_tag({action: :Search, id: @Search}, method: :get) do %>
		<%= search_field_tag :search_title %>
		<%= submit_tag '検索' %>
	<% end %>
</div><%# header %>

<% @videos.each do |video| %>
	<div class="videoindex">
		<div class="videoindexlink">
			<h2 class="title"><%= link_to video.title, video_path(video) %></h2>
			<% url = video.videourl.gsub(/http.+v=/, "") %>
			<%= link_to image_tag('http://i.ytimg.com/vi/' + url + '/hqdefault.jpg', width: 250), video_path(video) %>
		</div><%# videolink %>
		<div class="videoindextext">
			<%= simple_format(truncate(video.text, length: 400), class: :text) %>
		</div><%# videotext %>
		</div><%# videoindex %>
	<p class="username"><%= video.user.username %></p>
	<% if video.user_id == current_user.id %>
		<%= link_to '編集する', edit_video_path(video) %>
		<%= link_to '削除する', video_path(video), method: :delete, data: { confirm: '削除してもいいですか？' } %>
	<% end -%>
	<hr>
<% end -%>
<br>
<%= link_to 'トップへ戻る', videos_path %>

app/views/videos/new.html.erb
<h2>新規動画登録</h2>

<%= render 'form' %>

app/views/videos/show.html.erb
<h1><%= @video.title %></h1>
<% url = @video.videourl.gsub(/http.+v=/, "") %>
<%== '<iframe width="560" height="315" src="https://www.youtube.com/embed/' + url + '" frameborder="0" allowfullscreen></iframe>' %>
<%= simple_format(@video.text, class: :text) %>
<%= link_to '動画一覧へ戻る', videos_path %>